tmail:
  core:
    ttl: ${TTL:1}
  bot:
    token: ${TOKEN}
    telegram_url_pattern: ${TELEGRAM_URL_TEMPLATE:https://api.telegram.org/bot%s/%s}
    timeout: ${TIMEOUT:2}
  smtp:
    port: ${SMTP_PORT:2222}
    max_message_size: ${SMTP_MAX_MESSAGE_SIZE:5120}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  api:
    mailbox_host: ${MAILBOX_HOST:tmailbot.gq}
    time_format: "%s:%s"
